spring:
  application:
    name: reactjs-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/dha
#    url: jdbc:postgresql://172.21.0.3:5432/dha
    username: comrade
    password: dear
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  sql:
#    init:
#      mode: ALWAYS
springdoc:
  swagger-ui:
    path: /swagger-ui.html


reactjs:
  web:
    base-url: http://localhost:5173
    path: '/**'
    methods: DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT
  security:
    secret-key: dhaasajsjajsjashajsjajsashawueu8wue8uuwuiwejwnj3848348723723723878329490
    expiration-duration: 60
    token-header: Authorization
    token-prefix: "Bearer "