
 ------------------
 -- USER_ROLE
 -----------------

 CREATE TABLE IF NOT EXISTS USER_ROLE(
 USER_ID INT NOT NULL,
 ROLE_ID INT NOT NULL
 );
------------------
-- USER TABLE
------------

CREATE TABLE IF NOT EXISTS USER_PROFILE(
USER_ID  NOT NULL ,
EMAIL VARCHAR(50),
USER_NAME VARCHAR(10),
PASSWORD VARCHAR(20),
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
PHONE VARCHAR(13),
PASSWORD VARCHAR(255)
PRIMARY KEY(USER_ID)
);

--------------------
-- ROLES TABLE
-------------------

 CREATE TABLE IF NOT EXISTS ROLE(
 ROLE_ID SERIAL NOT NULL ,
 NAME VARCHAR(50),
 PRIMARY KEY (ROLE_ID)
 );




CREATE TABLE IF NOT EXISTS EVENT(
ID SERIAL NOT NULL,
IMAGE VARCHAR(255),
TITLE VARCHAR(255),
DATE VARCHAR(255),
PRIMARY KEY(ID)
);
 -------
 ---CONSTRAINT
 -------
--ALTER TABLE USER_PROFILE ADD COLUMN PASSWORD VARCHAR()
 --ALTER TABLE USER_ROLE ADD CONSTRAINT FK2x1053vp2bu7d5h332USER FOREIGN KEY (USER_ID) REFERENCES USER_PROFILE(USER_ID);
 --ALTER TABLE USER_ROLE ADD CONSTRAINT FK2x1053vp2bu7d5h332ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID);
